<?php

/**
 * Implements hook_page_attachments().
 */
function pusher_api_page_attachments(array &$attachments) {
  /** @var \Drupal\pusher_api\Factory\ConfigFactory $configFactory */
  $configFactory = \Drupal::service('pusher_api.config.factory');
  $defaultConfig = $configFactory->create();

  $attachments['#attached']['drupalSettings']['pusherApi'] = [
    'appId' => $defaultConfig->appId,
    'cluster' => $defaultConfig->options['cluser'],
  ];
  $attachments['#attached']['library'][] = 'pusher_api/api';
}
